AWSTemplateFormatVersion: '2010-09-09'
Description: Node app
Resources:
    InstanceSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupDescription: 'Instance security'
            SecurityGroupIngress:
                -
                  CidrIp: '0.0.0.0/0'
                  Description: 'SSH access'
                  FromPort: '22'
                  ToPort: '22'
                  IpProtocol: 'tcp'
                -
                  SourceSecurityGroupId: !GetAtt LoadBalancerSecurityGroup.GroupId
                  IpProtocol: -1
                  FromPort: 3000
                  ToPort: 3000
                
    LoadBalancerSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupDescription: 'HTPP access'
            SecurityGroupIngress:
                -
                    CidrIp: '0.0.0.0/0'
                    Description: 'Allowed from anywhere'
                    FromPort: '80'
                    ToPort: '80'
                    IpProtocol: 'tcp'   
                                  
    EC2Instance1:
        Type: 'AWS::EC2::Instance'
        Properties:
            AvailabilityZone: us-east-2b
            ImageId: 'ami-02bcbb802e03574ba'
            InstanceType: 't2.micro'
            KeyName: 'julianoalberto'
            SecurityGroupIds:
                - !GetAtt InstanceSecurityGroup.GroupId
            UserData:
              Fn::Base64:
                Fn::Join:
                  - ""
                  -
                    - "#!/bin/bash -ex"
                    - "\n"
                    - "sudo yum update -y"
                    - "\n"
                    - "sudo amazon-linux-extras install -y epel"
                    - "\n"
                    - "sudo yum install -y nodejs"
                    - "\n"
                    - "sudo yum install -y git"
                    - "\n"
                    - "cd ~"
                    - "\n"
                    - "git clone https://github.com/julianoalberto/hello-world.git"
                    - "\n"
                    - "cd hello-world"
                    - "\n"
                    - "npm install"
                    - "\n"
                    - "node . &"
                    - "\n"

    EC2Instance2:
        Type: 'AWS::EC2::Instance'
        Properties:
            AvailabilityZone: us-east-2c
            ImageId: 'ami-02bcbb802e03574ba'
            InstanceType: 't2.micro'
            KeyName: 'julianoalberto'
            SecurityGroupIds:
                - !GetAtt InstanceSecurityGroup.GroupId
            UserData:
              Fn::Base64:
                Fn::Join:
                  - ""
                  -
                    - "#!/bin/bash -ex"
                    - "\n"
                    - "sudo yum update -y"
                    - "\n"
                    - "sudo amazon-linux-extras install -y epel"
                    - "\n"
                    - "sudo yum install -y nodejs"
                    - "\n"
                    - "sudo yum install -y git"
                    - "\n"
                    - "cd ~"
                    - "\n"
                    - "git clone https://github.com/julianoalberto/hello-world.git"
                    - "\n"
                    - "cd hello-world"
                    - "\n"
                    - "npm install"
                    - "\n"
                    - "node . &"
                    - "\n"

    PlanetTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Name: PlanetTargetGroup
        VpcId: vpc-487b7720 #!Ref VPC
        Port: 80
        Protocol: HTTP
        Targets:
          - Id:
              Ref: EC2Instance1
            Port: 3000
          - Id:
              Ref: EC2Instance2
            Port: 3000

    PlanetLoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
          Name: PlanetLoadBalancer
          Subnets: 
            - subnet-5222163a
            - subnet-855a38ff
          SecurityGroups:
            - !GetAtt LoadBalancerSecurityGroup.GroupId

    LoadBalancerListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        LoadBalancerArn: !Ref PlanetLoadBalancer
        Port: 80
        Protocol: HTTP
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref PlanetTargetGroup